### ISSUE TITLE
Is there a figurehead and thought leader of some kind?

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#10]

**Comment by elear** [comment]
As of this date, it looks like there is consensus.

**Comment by mirjak** [comment]
Rather than just saying that there might be consensus it would be much more helpful to quickly capture here what the outcome of the list discussion was/is.

**Comment by elear** [comment]
Not yet consensus.

**Comment by elear** [comment]
There is consensus that we need to be careful about what to call the role ;-)

**Comment by cabo** [comment]
The binary issue is addressed by Section 6 of -00.
