### ISSUE TITLE
Allow for a temporary RSCE appointment while the permanent RSCE is still in post but temporarily unavailable

### ISSUE THREAD

**Issue by JayDaley** [intarchboard/program-rfced-future#104]
There are multiple reasons why the RSCE may be temporarily unavailable, including maternity leave, illness, or sabbatical, which the current draft doesn't allow for.  I suggest the following text be added:

> In the case that the RSCE is expected to be unavailable for an extended period then the IETF LLC may appoint a Temporary RSCE through whatever recruitment process it considers appropriate.  A Temporary RSCE acts as the RSCE in all aspects during their term of appointment

**Comment by elear** [comment]
No objections.

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/f19450e12dfb61dae595ea57c7e05b7422e9b8aa
