### ISSUE TITLE
RPC responsibilities list missing a couple of ex-(RFC Publisher) responsibilities

### ISSUE THREAD

**Issue by JayDaley** [intarchboard/program-rfced-future#105]
The list of RPC responsibilities in 4.3 needs a couple of tweaks:

> * Announcing and providing on-line access to RFCs.

could be expanded to:

> * Publishing RFCs by providing free and unrestricted online access both individually and in bulk, and by depositing copies in external archives.
> * Publishing catalogs and catalog entries, both individually and in bulk, for RFCs.
> * Announcing the publication of new RFCs to all interested parties.

**Comment by elear** [comment]
* Publishing RFCs, which includes:
 - depositing copies on the RFC Editor site both individually and in collections 
 - depositing copies with external archives 
 - creating catalogs and catalog entries
 - announcing the publication to all interested parties

**Comment by stpeter** [comment]
This change will be in -06

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/f6f3a36cd720dad6248e841a120b5c3b2e0fb226
