### ISSUE TITLE
Remove the word "ultimate"

### ISSUE THREAD

**Issue by mirjak** [intarchboard/program-rfced-future#108]
as in "ultimate authority of the IETF LLC" as I guess the *ultimate* authority actually lies with the community :-)

**Comment by mirjak** [comment]
Also I actually proposed on list to not talk about "authority of the IETF LLC" but use "contractually overseen by the IETF LLC” instead as we use it already once in the document. I think this is more accurate.

**Comment by stpeter** [comment]
I think we can close this issue in favor of the resolution in #122

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/f6f3a36cd720dad6248e841a120b5c3b2e0fb226
