### ISSUE TITLE
Do we want to write the existence of rfc-interest@rfc-editor.org in stone?

### ISSUE THREAD

**Issue by mirjak** [intarchboard/program-rfced-future#109]
The documents says

```
Notices will always be sent to the rfc-interest mailing list.
```

This assumes that we will "forever" have an rfc-interest@rfc-editor.org mailing list. Should we maybe rather specify what the purpose of his list is than attaching the procedures in this draft to a specific list name?

**Comment by stpeter** [comment]
List discussion seemed to indicate "the rfc-interest mailing list or an equivalent"

**Comment by stpeter** [comment]
I suggest: 

> Notices will always be sent to the rfc-interest mailing list or to its successor or future equivalent

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/f6f3a36cd720dad6248e841a120b5c3b2e0fb226
