### ISSUE TITLE
selection committees (again)

### ISSUE THREAD

**Issue by mirjak** [intarchboard/program-rfced-future#111]
We have two selection committees established by the LLC in the draft - one for the RPC vendor and one for the RSCE.

For the RPC vendor we say:

```
      The IETF LLC establishes a selection committee, which will consist
      of the IETF Executive Director and other members selected by the
      IETF LLC in consultation with the stream managers.
```

For the RSCE we say:

```
   The IETF LLC will form a selection committee, including members from
   the community, that will be responsible for making a recommendation
   to the IETF LLC for the RSCE role.
```

There are two differences here 1) naming the Executive director explicitly as a member and 2) consultation with the stream managers.

Just checking if we think these differences are intentional? And if so, why?

**Comment by stpeter** [comment]
Based on list discussion, I think we concluded that no change is needed from -05.
