### ISSUE TITLE
Minor:  RPC Statement of Work

### ISSUE THREAD

**Issue by mirjak** [intarchboard/program-rfced-future#112]
The draft says:

```
   The IETF LLC develops the work definition (the Statement of Work) for
   the RPC and manages the vendor selection process.  The work
   definition is created within the IETF LLC budget and takes into
   account the needs of stream managers as well as community input.
```

Just for the sake of completeness, shouldn't this sentence also say that the statement of works takes the list of RPC responsibilities in this draft in section 4.3 into account? Or is there actually a reason we don't say that explicitly?

**Comment by martinthomson** [comment]
> The work definition is created within the IETF LLC budget and takes into account the text in Section 4.3, the needs of each of the streams, and community input.

(The needs of stream managers is a subset of the needs of streams. Happy to take that to another issue.)

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/7d8b3f58e6fb93d9d1d8f0b29f0c534524ca4361
