### ISSUE TITLE
"Heritage"

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#119]
From Stephen Farrell:

> There is only brief mention that the RFC series has some
heritage. I think that'd be better expanded to include some
guidance for the RSWG that the preservation and propagation
of the positive parts of that heritage is a goal for the
RSWG. I don't think we ought try define that heritage (as
that'd likely be hard/controversial and very nitty) but a
total lack of guidance along those lines seems wrong to
me. That might take a bit of wordsmithing but the editor
may be best placed to start that.

**Comment by elear** [comment]
Proposed text:

>  All parties are encouraged to, respect the value of each stream and
> the long-term health and
>  viability of the RFC Series, and to give consideration for both the
> factors that have led to the series'  wide acceptance, and those that
> require it to evolve to see to its continued success.

**Comment by martinthomson** [comment]
Too many commas:

>  All parties are encouraged to, respect the value of each stream and the long-term health and viability of the RFC Series. Consideration is due for the factors that have led to the series' wide acceptance and for changes that might better serve the continued success of the RFC Series.

(My attempt at copy-edit.)

**Comment by mirjak** [comment]
Just want to note that we have this text in the intro this draft:

```
Under the auspices of this program, the community considered changes that would increase transparency and community input regarding the definition of policies for the RFC Series as a whole, while at the same time ensuring the continuity of the RFC Series, maintaining RFC quality, maintaining timely processing, ensuring document accessibility, and clarifying lines of authority and responsibility.
```
