### ISSUE TITLE
Is the expert an advisor (RSA) vs an executive editor (RSE).

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#12]
Only necessary to resolve if there is such an expert.

**Comment by elear** [comment]
Consensus check begins today to see if we agree that-

- role of the chair and the RS[EA] should be split.
- that person can raise issues to the strategic group
- the person does not make strategic decisions but that those are decided by the strategic body
- the person does not direct the RPC/REP.

**Comment by elear** [comment]
Now proposed baseline text at https://github.com/intarchboard/rfced-future/blob/master/Issue12-RSE-role.md.

**Comment by elear** [comment]
Comment period has passed.

**Comment by elear** [comment]
Please incorporate text from https://github.com/intarchboard/program-rfced-future/blob/master/Issue12-RSE-role.md

**Comment by stpeter** [comment]
I've taken that text and trimmed it down somewhat. We can discuss on list after publication of the next version. Current text in my working draft is:

> The RFC Series Editor/Advisor (RSEA) is a senior technical
> publishing professional who will apply their deep knowledge of
> technical publishing processes to the RFC series.

> The primary responsibilities of the RSEA are as follows:

> * Serve as a voting member on the RSAB.
> * Identify problems with the RFC publication process and opportunities for improvement.
> * Provide expert advice regarding policy proposals within the RSWG.
> * If requested, provide expert advice to the RPC and IETF LLC.

> Matters on which the RSEA might be consulted could include proposed
> changes to the RFC style guide {{RFC7322}}, RFC formatting in general,
> web presence, copyright matters, archiving policy, and dissemination
> and cataloguing of RFCs.
