### ISSUE TITLE
Section on External Representation does only consider incoming requests but not actual representation

### ISSUE THREAD

**Issue by mirjak** [intarchboard/program-rfced-future#121]
The section on "External Representation" only specifies how other can ask question but it doesn't actually say anything about representation when we need to reach out.

(Trying to capture an issue for one of the things that are under discussion on the list)

**Comment by elear** [comment]
This was previously and recently discussed and we agreed not to specify outbound outreach.

**Comment by elear** [comment]
This was part of the discussion for Issue #83.

**Comment by mirjak** [comment]
#83 also only discussed about having a contact point and we addressed that. But external representation should maybe also say something about who would go anywhere and talk about the RFC series. Or actually also internal representation is not fully clear I think: E.g. would be still have someone to give an update at the IETF Admin plenary?

**Comment by mirjak** [comment]
Okay. Not a super immortal point to me. Fine to close this issue. One editorial question though: would it make sense to change the heading of this section then?

**Comment by elear** [comment]
Which heading?  That sounds editorial.  If you can make a suggestion, Peter can consider it.

**Comment by mirjak** [comment]
There is a section called "External Representation" which then only talk about the existence of this mailing address.

**Comment by elear** [comment]
Ah right.  Point of Contact?

**Comment by mirjak** [comment]
works for me. Peter can decide this.

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/f6f3a36cd720dad6248e841a120b5c3b2e0fb226
