### ISSUE TITLE
"RPC under authority of the IETF LLC" => "as contractually overseen by the IETF LLC"

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#122]
From Mirja:
> Also I actually proposed on list to not talk about "authority of the IETF LLC" but use "contractually overseen by the IETF LLC” instead as we use it already once in the document. I think this is more accurate.

This would require changes in the abstract, Section 1, Section 2, Section 3.1.2, Section 4.1, and A.4.

**Comment by elear** [comment]
Ok to proceed.

**Comment by stpeter** [comment]
This change will be in -06.

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/f6f3a36cd720dad6248e841a120b5c3b2e0fb226
