### ISSUE TITLE
Mike St. Johns Editorials

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#123]
>
>
> Section 1, numbered item 1 beginning Policy definition.   This is worded in a way that implies more authority to the RSWG than is planned.  Instead replace the second sentence here (and the similar language in Section 2 third para with:
>
> "This is the responsibility of both the RFC Series Working Group (RSWG), which proposes policy, and the RFC Series Approval Board (RSAB), which evaluates and approves or rejects such proposals."

> Section 1, numbered item 2 top of page 4 first sentence: s/through publication of/of the concepts described in/.  Insert "Editorial" before "Series".

> Following para s/documents are produced/RFCs are produced/
Editorial
>
> Section 2, 3rd para change from above.  Also, that first sentence is a run on.

> Section 3, first para s/that are//  There are also missing commas.   Insert after (RSWG) - ", pass a community last call, "

> Section 4.1, 2nd para, last bullet, delete "contractually" - duplicative with "contract".

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/8e79840282e5409a9d440bdea5e8028dca0f92f5
