### ISSUE TITLE
Minor tweak to cover legacy RFC editor documents

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#124]
Mike StJohns:

> Section 4.1, 2nd para, first bullet.   I think some language is needed here such as insert at end: "or by such legacy RFCs which apply to the RPC and which have not yet been superceded by Editorial stream documents and the requisite contractual changes."

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/4ce67a1785831417eed409d75b75aac241672672
