### ISSUE TITLE
Point in time reference to RPC responsibilities

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#126]
Mike StJohns:

> Section 4.3 - first para: The RPC responsibilities will change from time to time and are specified by the contract, not by these documents unless incorporated by reference.  Suggest  inserting "(as of publication)" after "responsibilities" near the end of that long run on sentence.  Referencing the current contract may also be useful here.

**Comment by elear** [comment]
insure timelessness

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/52657265b9ea83a235cb61c342f12a3ecdc9e373
