### ISSUE TITLE
COI mods

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#127]
Mike StJohns:

> Section 5.3 - Suggest adding "The COI policy shall not preclude the RPC from contracting services from the person or entity performing the RSCE function.  Such contracts shall be disclosed publicly".  There are too few people that might want to engage with us, and the RPC may not want to pay a full time person for some of the tasks we've moved around.  I'd prefer making it explicit that the LLC can't make working for the RPC an unmanageable COI for the RSCE.

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/c157c3c759b368961fb2d9df9538d1f281a60cda
