### ISSUE TITLE
Permit RSCE not to wait to be consulted

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#128]
Last bullet, Section 5: remove "If requested"
Next sentence, change "RSCE might be consulted" to "RSCE might provide guidance".

**Comment by elear** [comment]
Ok to proceed.  People to object if they don't like the text in the draft.

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/39c8b8382c5bcdf7ce894e91149450ce583a53b0
