### ISSUE TITLE
What happens if the vote doesn't pass?

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#132]
From the mailing list...

> >  *  The RSAB considers those proposals and approves them, returns them
>       to the RSWG for further consideration, or declines to publish
>       them, as appropriate.
>
> It's actually not quite clear to me that the RSAB can decline to
> publish as distinct from just sending the proposal back. What
> would that consist of?

I think you're identifying an issue in terms of what happens if there is a vote, and there are not three votes to approve a proposal (bottom of § 3.2.2).  This document doesn't say what happens.  I think what we mean to say is this:

"If a vote is taken and the proposal is not approved, it is returned to the RSWG.  The RSWG can then consider making further changes."

That would match the intro text you quote.

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/1e7c2c85faa37f1a46e85b7b6db7763f3d6e799a

**Comment by elear** [comment]
This one needs a bit of additional text in the normative section, if a vote fails.

**Comment by stpeter** [comment]
ACK, will fix in -07.

**Comment by elear** [comment]
This still needs work.

**Comment by stpeter** [comment]
The WIP version of the draft (see https://github.com/intarchboard/program-rfced-future/commit/6e7f8ab2a80b04d628e97450d556e1c49776933d#diff-ca66d5135ef4d1afd63f78c044c9eb63ce44bf58f5f8fb2a8819329190d3ef45 for details) now says:

12. If, after a suitable period of time, any CONCERN positions remain,
    a vote of the RSAB is taken. If at least three voting members vote
    YES, the proposal is approved.

13. If the proposal is not approved, it is returned to the RSWG. The RSWG
    can then consider making further changes.

14. If the proposal is approved, a notification is sent to the community,
    and the document enters the queue for publication as an RFC within
    the Editorial Stream.

**Comment by elear** [comment]
Perfect.
