### ISSUE TITLE
How do we update This document?

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#134]
Mnot text:

> Updates, amendments and refinements of this document can be produced using the process documented here, but are only operative upon agreement of the IAB, the IESG, and the IETF LLC. Note that this does not preclude such changes from being defined outside this process, so long as the same agreement is found.

**Comment by elear** [comment]
MIrja:

> "Updates, amendments and refinements of this document require agreement of the IAB, the IESG, and the IETF LLC."

**Comment by elear** [comment]
@stpeter please include text along the above lines in the next rev (choose which version you like).

**Comment by elear** [comment]
See discussion on list.

**Comment by stpeter** [comment]
Provisionally addressed by https://github.com/intarchboard/program-rfced-future/commit/41886825bc265b4a6d1d3e1caeb66aa49d620618 - the usual caveats apply.
