### ISSUE TITLE
Who chairs the strategic body?

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#14]
RSE/RSA, someone(s) appointed by the (IAB/ISOC)?

**Comment by elear** [comment]
Consensus check begins today to see if we agree on who **doesn't** chair (namely the RS[EA]

**Comment by martinthomson** [comment]
The RSWG needs chairs.  For this, I don't have any real opinion, but it might be that the RSAB can be given this responsibility.

The RSAB might need a chair.  The draft currently says that they appoint their own.  This seems reasonable to me.

**Comment by elear** [comment]
Text is now in draft -01.

**Comment by elear** [comment]
Slight tweak for staggered terms.  Separate issue #72 opened to address chair removal.  Issue #71  also discusses possible term limits.

**Comment by elear** [comment]
Peter to add the tweak about staggered terms.  Consensus call completed.

**Comment by stpeter** [comment]
This text is in version -01 so I suggest we can close the issue now.
