### ISSUE TITLE
Is there a public archive for the RSAB email list?

### ISSUE THREAD

**Issue by stpeter** [intarchboard/program-rfced-future#143]
Raised by Brian Carpenter on list: "As far as I can see, we don't specify whether the RSAB's mailing list does, or doesn't, have a public archive."

**Comment by becarpenter** [comment]
Opinion: Preferably, the list archive will be public, but in that case there will also need to be a -private list for "executive session" discussions.

**Comment by stpeter** [comment]
Provisionally addressed by https://github.com/intarchboard/program-rfced-future/commit/9166568e407e553e85b32d4a3cb9b0579fca4991 - subject to revision, consensus still to be verified on list.

**Comment by stpeter** [comment]
Now see also https://github.com/intarchboard/program-rfced-future/commit/6c492105eaed2afa51a3353a938b9871184d145d
