### ISSUE TITLE
Other modes of operation

### ISSUE THREAD

**Issue by ekr** [intarchboard/program-rfced-future#144]
The current document says:

>  When the RSWG is formed, all discussions shall take place on an open
   email discussion list, which shall be publicly archived.
   Subsequently, the RSWG may decide by rough consensus to also use
   additional tooling (e.g., GitHub as specified in [RFC8874]), forms of
   communication (e.g., in-person or online meetings), and working
   methods (e.g., design teams) as long as they are consistent with
   [RFC2418].

I understand that there are people who want to require a new finding of
consensus to use Github, and that's fine, but this text seems to require
rough consensus to schedule a meeting -- or at least to schedule the
first one. That seems too restrictive. If others agree, I can propose text
to allow the normal IETF-like modes of operation but carve out the
Github exception.

**Comment by elear** [comment]
Please take to the list.

**Comment by stpeter** [comment]
Suggested text:

> When the RSWG is formed, all discussions shall take place on an
open email discussion list, which shall be publicly archived. The
RSWG is also empowered to hold in-person or online meetings. The RSWG
may also decide by rough consensus to use additional tooling (e.g.,
GitHub as specified in {{RFC8874}}), forms of communication,
and working methods (e.g., design teams) as long as they are
consistent with {{RFC2418}}.

**Comment by stpeter** [comment]
I wonder if we need to say something about advance notice for meetings...

**Comment by ekr** [comment]
Can we just steal text from the IETF rules about meetings?

**Comment by stpeter** [comment]
I guess that would be https://www.ietf.org/about/groups/iesg/statements/interim-meetings-guidance-2016-01-16/

Let me see if I can boil it down. Also I will bring this to the list.

**Comment by stpeter** [comment]
Provisional text checked in via https://github.com/intarchboard/program-rfced-future/commit/2fc8190c59d304f289003921ba7fb70b66bf6b08 - the usual caveats apply.
