### ISSUE TITLE
CONCERN for unaddressed comments

### ISSUE THREAD

**Issue by ekr** [intarchboard/program-rfced-future#145]
I apologize for the late notice, but I just noticed the following reason for a CONCERN position:

>    *  Comments received during a community call for comment need to be
      addressed, as described under Section 3.2.3.

This seems like it allows the RSAB to launder an objection for any reason other than the previous two (harm to a stream or the  series) by just saying that a community member objected. My memory is that that list was intended to be exclusive and so therefore I think we should strike or narrow this last reason so that the objections themselves need to be for one of the above two reasons.

**Comment by ekr** [comment]
To add to this, I would have expected that one could appeal an RSAB CONCERN on the grounds that it was for an invalid reason (E.g., I just don't like the spelling in this document)   but S 3.2.4 seems to be unclear on this point.

**Comment by elear** [comment]
Please take to the list.

**Comment by stpeter** [comment]
See https://github.com/intarchboard/program-rfced-future/commit/3e902e8cd91e9fd710efa3dfa4b7b018a83ce189 - no consensus for this yet, the usual caveats apply.
