### ISSUE TITLE
Core RPC responsibilities

### ISSUE THREAD

**Issue by ekr** [intarchboard/program-rfced-future#146]

**Comment by ekr** [comment]
>   The core responsibility of the RPC is continuous improvement
   regarding the implementation of RFC policies (including the
   dimensions of document quality, timeliness of production, and
   accessibility of results), while taking into account issues raised by
   the community through the RSWG and by the stream approving bodies.
   More specifically, the RPC's responsibilities at the time of writing
   include the following:

I appreciate the kaizen rhetoric, but it seems to me that actually the core responsibility is to keep publishing RFCs (the RFCs must flow!). I'd be happy to provide some new text if you agree @stpeter

**Comment by elear** [comment]
I think this is editorial, but please take to list with a simple editorial change.

**Comment by stpeter** [comment]
Good catch. Here is suggested text:

> The core responsibility of the RPC is the implementation of RFC Series
policies through publication of RFCs (including the dimensions of document
quality, timeliness of production, and accessibility of results), while
taking into account issues raised by the community through the RSWG and
by the stream approving bodies.

**Comment by ekr** [comment]
LGTM
