### ISSUE TITLE
Does the RPC create and preserve records

### ISSUE THREAD

**Issue by ekr** [intarchboard/program-rfced-future#147]
S 4.3 says that the RPC has the responsibility to "Creating and preserving records of edits performed on documents.". Does this happen now? I am not aware of where to find them.

**Comment by ekr** [comment]
Similarly    "Creating and preserving records of dialogue with document  authors." 

Is there some policy here or is it just in people's mailboxes?

**Comment by elear** [comment]
You can ask the RPC, or otherwise please take to list.
