### ISSUE TITLE
Who makes final decisions on strategy?

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#15]
Is it the strategic body or the RSE?

**Comment by elear** [comment]
Repurposing more broadly.

**Comment by elear** [comment]
Who makes strategic decisions?
 - is it the RS[EA]
 - is it a WG model?
 - is it a board model?

**Comment by huitema** [comment]
As I mentioned in the chat room during the meeting yesterday (12/17/2020), I think a working group model works better if there is a review body on top, so the proposal would be:

* strategic directions are discussed in a WG and documented in WG drafts,
* once the WG chairs determine consensus, the draft is passed to the review body for approval,
* (maybe) have a community wide last call at this stage, so the community is not surprised by WG decisions,
* the review body may then either approve, or send the document back to the WG.

There were suggestions during the meeting that the review body would be constituted of the stream editors, ex officio. I think that would be fine.

**Comment by elear** [comment]
@huitema Thanks, Christian.  Would you kindly send that to the program for discussion?

**Comment by elear** [comment]
Propose to close, based on text in document.  2 week call needs to be sent.

**Comment by elear** [comment]
Proposed to close and call issued.

**Comment by elear** [comment]
Email sent on 25 May
