### ISSUE TITLE
Consultation regarding the RSCE selection committee

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#151]
There has been discussion on list regarding whether the RSAB should be consulted either during or as an approval step to create the selection committee.

**Comment by stpeter** [comment]
I've proposed text on list:

   Responsibility for making a recommendation to the IETF LLC regarding
   the RSCE role will lie with a selection committee.  The IETF LLC will
   propose an initial slate of members for this committee, making sure
   to include members from the community, and consult with the stream
   representatives regarding the final membership of the committee.  In
   making its recommendation for the role of RSCE, the selection
   committee will take into account the definition of the role as well
   as any other information that the committee deems necessary or
   helpful in making its decision.  The IETF LLC is responsible for
   contracting or employment of the RSCE.

**Comment by stpeter** [comment]
Provisionally checked in at https://github.com/intarchboard/program-rfced-future/commit/453ceed5f71d4e804627d77a7ce5b64e9bb1da20 (subject to change based on further discussion).
