### ISSUE TITLE
Paul Hoffman Comments

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#154]
Greetings again. The structures proposed in this document seem like a very good way forward. The level of detail about the expectations on each group is a good balance in prescriptiveness.

Two small thoughts on the current draft:

The future status of the rfc-interest mailing list is unclear; see Section 3.2.3. Given it s current contents, I could see that it would easily become a parallel track for discussions that should be on the RSWG mailing list. It might be good to close (and certainly archive!) rfc-interest unless it becomes more moderated by someone pointing discussions to the RSWG.

Someone is going to have to tool the tracking for RSWG documents after they leave the RSWG, given that this is a new process. That might be informal (but public) tracking, but I suspect that formally tracking the various rfc799*-bis documents will prevent later issues from arising based on missed cross-dependencies. Maybe adding a sentence or two about this to the current draft will keep it in our minds as we move forward.

--Paul Hoffman

-- 
Rfced-future mailing list
[Rfced-future@iab.org](mailto:Rfced-future@iab.org)
https://www.iab.org/mailman/listinfo/rfced-future

**Comment by stpeter** [comment]
This comment was addressed in -13 so I think we can close the issue.
