### ISSUE TITLE
Colin Perkins Comments

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#155]
On re-reading this draft, I noticed the following two points:

§3.1.1.4: "The intent is that the RSWG shall operate in a way similar to working groups in the IETF and research groups in the IRTF."

§3.2.2: "the RSWG may adopt the proposal as a draft proposal of the RSWG, in much the same way a working group of the IETF or research group of the IRTF would"

There are some significant differences in the way IRTF and IETF groups are permitted to operate. To avoid confusion, these sections might be better phrased by omitting the references to IRTF.

Apologies that I didn’t catch these earlier.

Colin

**Comment by stpeter** [comment]
This comment was addressed in -13 so I think we can close the issue.
