### ISSUE TITLE
Who handles oversight/appeals?

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#16]
Oversight/appeals remains with the IAB vs moves to ISOC vs moves to RSEB

**Comment by elear** [comment]
As discussed today, 

RFCWG: 
Process only only.  RSAB is a natural checkpoint.  RSAB will also satisfy itself that WG process was followed, doesn’t conflict with existing policy without explicitly changing it, and that rough consensus was established.

No decision yet on RSAB.

**Comment by elear** [comment]
latest text for the RSAB:

Appeals of RSWG decisions can be made to the RSAB if there are concerns about the process followed by the RSWG chairs.  Appeals should be made within 30 days of any action.  The RSAB then decides if the process has been followed and can direct RSWG chairs in what procedural actions are required.

**Comment by elear** [comment]
Updated proposed text:

> Decisions of the RSWG can only be appealed on grounds of failure to 
follow the correct process. Appeals should be made within 30 days of 
any action, or in the case of failure to act, of notice having been 
given to the RSWG. The RSAB will then decide if the process was 
followed and will direct RSWG chairs as to what procedural actions are 
required.

**Comment by elear** [comment]
The following needs to get wordsmithed into text in the draft:

> Include a sentence or two in the document saying that the chairs are required to follow the rough consensus of the working group?   And further that in process matters the RSAB is requried to respect the rough consensus of the working group...

**Comment by stpeter** [comment]
Version -01 says:

> The RSWG shall operate by rough consensus, a mode of operation informationally described in [RFC7282].

and:

>    It is the responsibility of the chairs to encourage rough consensus within the RSWG and to follow that consensus in their decision making, for instance regarding advancement of proposals to the RSAB.

and:

> It is expected that the RSAB will respect the rough consensus of the RSWG wherever possible, without ceding its review function.

So I think we can close this issue?

**Comment by elear** [comment]
This requires a final consensus check.

**Comment by elear** [comment]
Propose to close: August 17 deadline.
