### ISSUE TITLE
Decider for hiring RSA/RSE?

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#20]
IAB? RSEB? ISOC BOT? LLC?  ED? Other?

**Comment by elear** [comment]
"The RSEA will be selected by a committee formed by the Executive Director of the IETF LLC, taking into account the role definition [13] and any detailed job description defined by the relevant parties"

**Comment by stpeter** [comment]
s/committee/search committee/

**Comment by elear** [comment]
New text has been developed from the meeting on 29/30 July.

**Comment by elear** [comment]
I'm going to close this issue as a duplicate of Issue 40.
