### ISSUE TITLE
Is there a new, separate Editorial Stream?

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#22]

**Comment by larseggert** [comment]
I'd really like to avoid creating a separate mini-stream. Is the IAB stream not acceptable here?

**Comment by elear** [comment]
General agreement that there should be a new editor stream.  Confirm on mailing list.

**Comment by stpeter** [comment]
Version -01 of the draft says:

>    This document creates the Editorial Stream. Any and all future documents produced by the RSWG and approved by the RSAB shall be published in the Editorial Stream.

**Comment by stpeter** [comment]
@elear I think we have text and consensus on this - shall we close the issue?

**Comment by elear** [comment]
We need to consensus check this one.

**Comment by stpeter** [comment]
Fine by me. :-)

**Comment by elear** [comment]
Chairs see that the consensus is for a new stream.
