### ISSUE TITLE
Who writes the SOW?

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#25]

**Comment by elear** [comment]
Jay: LLC can write the SOW and circulate with the community for comment.

**Comment by stpeter** [comment]
Actually, version -01 already said:

>   The IETF LLC develops the work definition (the Statement of Work) for
>   the RPC and manages the vendor selection process.  The work
>   definition is created within the IETF LLC budget and takes into
>   account the stream managers and community input.

**Comment by elear** [comment]
This one is in consensus check.
