### ISSUE TITLE
Do we need to update BCP79?

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#28]
From John:

Intellectual Property Rights in IETF Technology (RFC8179/BCP79)
(while IETF-specific, also adopted by the IRTF
(https://irtf.org/policies/ipr)

  Summary: This document/BCP is essentially about patents
  which, as far as I can tell, have not in the past and
  should not in the future impact the RFC Editor.

  Action required: Probably not, but requiring conformance
  along the lines of the IRTF policy would not be harmful.

**Comment by stpeter** [comment]
Agreed, I'd prefer not to touch this one in any way (and it seems unnecessary).

**Comment by elear** [comment]
Please add one line indicating that contributions through this process are covered by BCPs 78 and 79.

**Comment by elear** [comment]
See Issue #29
