### ISSUE TITLE
Do we need to update BCP 39? (IAB Charter)

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#30]
From John:

Charter of the Internet Architecture Board (IAB) (RFC
2850/BCP0039)

  Summary: Mentions responsibility for the RFC Editor. It also
  specifies that the RFC Editor is an liaison member of the
  IAB. Depending on what other decisions we make, that may no
  longer be appropriate and we may need to sort out whether
  the RSE/A, RPC, or both, should have liaisons to the IESG.
  It also occurs to me that having the RSE/A be an ex-officio
  member of the LLC Board might improve communications,
  facilitate discussion of tradeoffs about possibly courses of
  action that would require money or other resources, and
  provide a barrier against treating the RSE/A and/or the
  entire RFC Editor Function as "just contractors".

  Action required: If we continue on what I think is our
  current path, the IAB responsibility for the RFC Editor
  will need to come out.   And we need to sort the liaison
  issues out.

**Comment by stpeter** [comment]
My initial take is that, while the IAB might want to consider updating BCP 39 (and we might want to suggest to the IAB that one reason for doing so could be publication of the RFC Editor Model Version 3), the latter document does not need to formally update RFC 2850 / BCP 39.

**Comment by elear** [comment]
There is now a draft that needs to be dispatched.

**Comment by elear** [comment]
This issue will close as Brian's draft hits the IAB.
