### ISSUE TITLE
Do we need to update Anti-Harrassment policy and WG procedures to make them applicable to WG?

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#34]
From John:

IETF Anti-Harassment Procedures (RFC 7776/RFC 8716)

  Summary: this document is veryfocused on the IETF.  If
  the strategic and policy activities of the RFC Editor
  Function are going to be treated as a new and separate body,
  similar rules, ideally tracking the IETF ones as they
  evolve, are probably in order.  It would seem sensible to
  piggyback on the IETF process, including using the IETF
  Ombudsteam structure, advisors, and membership if the IETF
  is willing, but there could be bad optics if someone
  associated with a non-IETF interest in the series got into a
  harrassment dispute with people active in the IETF and
  apparently trying to advocate its interests against those of
  other groups.

  Action required: Decide whether we are concerned about the
  risks of using an IETF process and team.   If we decide we
  are nor (or that the risks are acceptable), work out details
  with the IESG and create documentation incorporating their
  rule and system.  If not, we would need to figure out
  whether the RFC Editor Function or its strategic and policy
  components need their own policy and build and document
  that.

**Comment by elear** [comment]
Where we got hung up in our last interim meeting was understanding precisely what it would mean to apply WG procedures to this new WG that does not report into the IESG. You discussed the ramifications of this.  Thank you.  I believe the intent of the group (and people should be free to disagree) is that we do a pass on BCP 25 that includes RFCs 2418, 3934, 7776 (and 7437 by extension), and 8716, to see if we can substitute roles of area directors for some other people.

**Comment by larseggert** [comment]
Do we really need to do all this work on BCP25? I'll note that for example the IRTF has no issue to simply say "these IETF rules also apply to us" without the respective IETF rules needing an update to (also) say that.

**Comment by stpeter** [comment]
I will draft text, including the issue of when quorum is achieved if necessary.

**Comment by elear** [comment]
He did this.  Text is there.
