### ISSUE TITLE
How to select the RSWG chairs?

### ISSUE THREAD

**Issue by mirjak** [intarchboard/program-rfced-future#41]
The draft says:

`The IETF Chair and the Independent Submissions Editor shall each appoint and oversee a co-chair of the RSWG.`

I don't have an opinion if that is the right thing to do or what's the right thing to do but this proposal came out of nothing without much discussion in the group, so at least I would like to see some discussion.

**Comment by mirjak** [comment]
And related (but I guess could also be an own issue): I think we should also say more about how to eventually "get rid" of the chairs. "Firing" chairs is the most difficult task as AD but for long-standing efforts it's usually really good to have some rotation. So maybe we needs terms for the chairs or something...

**Comment by stpeter** [comment]
> The draft says:
> 
> `The IETF Chair and the Independent Submissions Editor shall each appoint and oversee a co-chair of the RSWG.`
> 
> I don't have an opinion if that is the right thing to do or what's the right thing to do but this proposal came out of nothing without much discussion in the group, so at least I would like to see some discussion.

The -00 version was just a strawman (I believe that text came from the chairs' proposed text). So yes, this needs discussion on the list.

**Comment by larseggert** [comment]
Wondering if the IAB Chair would be a better option than the ISE, given that the IAB has direct or indirect oversight over all the non-IETF streams. I understand that some folks might want to strengthen the standing of the Independent Stream, but I question whether this is the correct way to do this.

**Comment by larseggert** [comment]
> I think we should also say more about how to eventually "get rid" of the chairs. 

It would be most logical if the person/role appointing a chair is also the one that will replace them at their discretion.

**Comment by elear** [comment]
Discussions here will carry absolutely **NO WEIGHT** in working group considerations.  Please take them to the list.

**Comment by stpeter** [comment]
As Adrian noted in https://github.com/intarchboard/program-rfced-future/issues/42 additional constraints might include:

* nominations period
* open feedback period
* length of term
* number of terms

To be discussed on list, of course.

**Comment by stpeter** [comment]
See proposed text in draft-saintandre-rfced-model-01.

As Adrian Farrel noted, we should stagger the terms (e.g., initial terms of 2 and 3 years, then 2-year terms after that). The text needs to be adjusted to address this aspect.

**Comment by stpeter** [comment]
Version -01 of the draft says:

>   The RSWG shall have two chairs, one appointed by the IESG and the
>   other appointed by the IAB.  When the RSWG is formed, the chair
>   appointed by the IESG shall serve for a term of one (1) year and the
>   chair appointed by the IAB shall serve for a term of two (2) years;
>   thereafter, chairs shall serve for a term of two (2) years, with no
>   term limits on renewal.  The appointing bodies shall determine their
>   own processes for making these appointments, such as provision for an
>   open nominations period.  Community members who have concerns about
>   the performance of an RSWG chair should direct their feedback to the
>   relevant appointing body.  Each appointing body shall have the power
>   to remove its appointed chair at its discretion.
