### ISSUE TITLE
Lars Eggert comments

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#46]
We can break these out if these is controversy.

Hi,

On 2021-4-5, at 22:19, Peter Saint-Andre <stpeter@mozilla.com> wrote:
https://datatracker.ietf.org/doc/draft-saintandre-rfced-model/

I gave this a quick read, below are some initial thoughts.

Thanks,
Lars

Section 4, paragraph 2, comment:
  Continuing publication of RFCs shall be handled by the RFC Production
  Center (RPC) function in accordance with current policies in force or
  future policies defined as specified in the next section of this
  document.

I'm not quite sure what "Continuing publication" is meant to express - can
"continuing" be removed, or else, what does it signify? (Or was the intent to
say "Publication ... shall continue to be handled"?)

Section 5.1.1, paragraph 1, comment:
5.1.1.  RFC Series Working Group (RSWG)

Calling this group a Working Group will likely be a constant source of confusion
for IETF participants that do not pay much attention to organizational
discussions, because this group will be significantly different from "real" IETF
WGs. I'm wondering if calling it a "Policy Group" or by some other name may reduce
that possibility for confusion.

Section 5.1.1, paragraph 2, comment:
  The IETF Chair and the Independent Submissions Editor shall each
  appoint and oversee a co-chair of the RSWG.

I can understand why each separately appoints one chair, but why would each then
continue to oversee only the one chair they appointed?

Section 5.1.2, paragraph 4, comment:
  The voting members of the RSAB shall be as follows:

Are there members other than voting members on the RSAB? If not, just call them
members? If yes, who are they?

Section 5.1.2, paragraph 7, comment:
Is there an intention for the RSAB to gain additional (voting) members
if new RFC streams are created in the future?

Section 5.2.2, paragraph 18, comment:
  1.  If a CONCERN exists, discussion will take place within the RSWG.
      Again, all RSAB members MUST participate.

This is an unenforceable MUST.

Section 5.2.2, paragraph 18, comment:
  2.  If all CONCERN positions are addressed, then the proposal is
      approved.  Again, if substantial changes have been made, an
      additional call for community input should be made.

It's not quite clear what "addressed" means. It would be clearer to say "A
proposal without any CONCERN positions is approved."

Section 6.1, paragraph 2, comment:
  process in confidence.  The initial length of service shall be for
  one year, but then further extensions will be for three to five
  years.

It will IMO be difficult to hire the desired senior professional on a one-year
contract.

**Comment by stpeter** [comment]
I believe that we've addressed this feedback via versions -00 and -01 of the program draft, but if not perhaps @larseggert could let us know. :-)

**Comment by elear** [comment]
I've sent a note to the list

**Comment by elear** [comment]
Closing this, but have opened Issue #80 as discussed.
