### ISSUE TITLE
What is success?

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#47]
From Mike St John:
As a general comment on the document and its structure:  The document does a reasonable job of describing the control process, but fails at describing how to achieve "success" of the RFC Editor process or even describing what "success" looks like.  While I know we have not yet come to an agreement (and may not) about what success is, there ought to be a structured place in this document that describes it, and the meta process for achieving it.

I.e., the fact that the RSWG can originate various proposals may be of interest, but having an overarching agreed upon skeleton on which the proposals may be laid and against which the RSAB can evaluate said proposals seems to be critical preventing a failure of the process.

**Comment by elear** [comment]
Perhaps this is a mission statement.  Maybe this is the early deliverable of the RSWG, to set principles on which people find agreement.  This requires additional thought and text.

**Comment by elear** [comment]
@elear to post 8729 mission statement, as well as what do we have to do next?

**Comment by stpeter** [comment]
Based on comments from Brian Carpenter, I'm not sure we need to keep this one open: https://mailarchive.ietf.org/arch/msg/rfced-future/h0TOz6z5a4ET2qUGWh6YgWG1jYY/ - he suggests that this issue might be covered by https://github.com/intarchboard/program-rfced-future/issues/31
