### ISSUE TITLE
Can the RSAB do anything other than evaluate work from the WG?

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#50]
The first paragraph of section 5.1.2, specifically the sentence beginning "The sole function..." does not appear to represent a consensus, and from my point of view is likely to contribute to a failure of the process.

Basically, there needs to be a way for the RSAB to move documents along that they believe are necessary to provide for the operation of their streams and the overall RFC series, even if they are unable to gain consensus within the RSWG.   And that assumes (and this is not necessarily valid) that the RSWG is both populated and functional.

Loud noises (or total silence) in the RSWG should not prevent the RSAB from authoring a document, providing it for community comment and publishing it to address a need the RSWG has no interest in addressing.

Section 5.2.2 must change to admit for RSAB originated documents.

**Comment by elear** [comment]
Note Jay's comments about the RSAB being part of the hiring  / review process.

**Comment by mnot** [comment]
> Section 5.2.2 must change to admit for RSAB originated documents.

'must' is too strong here. The RSAB members can already introduce a document into the WG, and ask the Chairs to expedite it.

If there is silence or polite disinterest, the document can still progress, based upon *some* level of interest in it (from the RSAB members).

If there is pushback, it needs to be worked through, just like anything else; if there's a particularly contentious issue, one side can be declared to be in the rough, just as always.
