### ISSUE TITLE
Do new streams imply new RSAB members?

### ISSUE THREAD

**Issue by stpeter** [intarchboard/program-rfced-future#53]
If new streams are created, should or will those streams automatically or by some well-defined process gain representation on the RSAB?

**Comment by larseggert** [comment]
IMO, yes.

(The reason I am thinking this is that when I was IRTF chair and the RSOC was interviewing for a new RFC Editor, I was forgotten to be included in this process until the very last second. This was apparently because all the other stream owners were RSOC members, but I was not. I would not like to see this repeated.)

**Comment by cabo** [comment]
Of course, that means that creating a stream also implies a change in power structure in the RSAB.  One may be desirable, the other not so.  Or it may create an incentive to lobby for creating a stream that wouldn't otherwise be considered.

Sorry for stating the obvious here.

**Comment by elear** [comment]
Add text that says that any new streams must specify whether the stream manager gets a seat on the RSAB.  To be confirmed on mailing list.

**Comment by elear** [comment]
Consensus that “any new streams must specify whether the stream manager gets a seat on the RSAB. To be confirmed on mailing list.”

**Comment by stpeter** [comment]
Proposed text (sent on list):

> Whenever a new stream is created {{RFC4844}}, the document that
> creates the stream shall specify if a voting member representing
> that stream shall also be added to the RSAB, along with any rules
> and processes related to that representative (e.g., whether the
> representative is member of the body responsible for the stream
> or an appointed delegate thereof).

**Comment by stpeter** [comment]
We have text in -01 and we haven't received any negative feedback, so I suggest we can close this issue @elear
