### ISSUE TITLE
Suggestions for ongoing RS[EA] evaluation (Jay Daley)

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#55]
Jay Daley:

> I’ve reviewed 6.2 "RSEA Ongoing Performance Evaluation" of draft-saintandre-rfced-model and I wonder if it is possible for a draft recommendation from the IETF Executive Director to be presented to the RSAB, excluding the RSEA, and an official view of the RSAB to be included in the final recommendation to the LLC Board?

> My concern here is that community feedback, while often of high quality, may potentially be biased or incomplete and the RSAB is probably best placed to take a view on that.

> Also, I think it would be useful to note why this recommendation has to go to the LLC Board rather than just being handled by the IETF Executive Director, otherwise this document may inadvertently set a precedent for other contracts.

> Finally, I assume the feedback, summary of feedback and the recommendation are confidential?  If not then that should be clearly stated.

Jay

**Comment by elear** [comment]
1. Community feedback to the LLC
2. LLC produces a draft performance evaluation for the RSAB (excluding the RSEA)
3. RSAB (excluding RSEA) provides feedback back to the LLC on that evaluation.

**Comment by elear** [comment]
Peter, s/ED/LLC/ and add steps 2 and 3 above.

**Comment by elear** [comment]
I think this one still needs one slight tweak in Section 4 (before 4.1):

s/and the IETF Executive Director//

**Comment by stpeter** [comment]
ACK

Note that we have the same text in §5.1:

> The exact relationship is a matter for the IETF LLC and the IETF Executive Director to determine.

Presumably we should make that change in both places?

**Comment by elear** [comment]
yes please

**Comment by stpeter** [comment]
Done.
