### ISSUE TITLE
Process for RPC work not requiring consensus

### ISSUE THREAD

**Issue by JayDaley** [intarchboard/program-rfced-future#56]
The RSWG/RSAB process is clear for larger projects but the RPC also need a path for discussion and agreement on smaller things that do not require a consensus process.  Previously the RPC would discuss and agree these with the RSE, with the RSE taking the decision on what meets the threshold for taking to the community.  How are those agreed now and who decides what does and does not need community consensus/engagement?

**Comment by elear** [comment]
This is the current basis on which we should develop text:

>     The RSWG establishes policy, with input from the community, the RSAB, and the RSEA.
>     The RSAB considers those proposals and approves or returns as appropriate.
>     The RPC periodically reports to the RSAB on how it is implementing that policy.
>     The RSEA provides expertise to the RPC and RSAB on how to implement the policy on an ongoing and operational basis, perhaps raising issues along the way for both the RSAB and community to consider.
>
> If issues arise with particular policies, the RPC still brings them to the RSAB who interprets the policy, and provides interim guidance to the RPC, informing the RSWG of those interpretations.

**Comment by elear** [comment]
Sorry- I think some text is still needed in the draft for this issue.
