### ISSUE TITLE
How are RPC priorities set?

### ISSUE THREAD

**Issue by JayDaley** [intarchboard/program-rfced-future#57]
The RPC has a wide set of projects to deliver with limited resources and decisions have to be made on priorities.  Previously this was negotiated between the RSE and RPC with the RSE having an understanding of community priorities.  How are the priorities set now?

**Comment by elear** [comment]
Linked to #61 and #62.  Resource implications negotiated with LLC.  Updated text needed.  Escalation over priorities is to the LLC.  How is feedback received and how is it answered?

Examples:
 - if one stream wants to change errata handling for that stream, that's something the RPC can manage.
 - Small changes just get on the work plan.
 - Big policy issues impacting other streams would have to go to the RSWG.

Mirja's point about the work plan, the work plan needs to be properly leveled (don't include small stuff, except perhaps as a "small stuff" bucket).
