### ISSUE TITLE
Who mediates disputes between the RPC and authors?

### ISSUE THREAD

**Issue by JayDaley** [intarchboard/program-rfced-future#59]
It’s not clear who mediates disputes between the RPC and Authors?

**Comment by elear** [comment]
As discussed today, stream managers are final arbiters for their stream policies.  Conflicts with cross-stream policies: RPC consults RSAB to determine whether issue is covered by existing policy and being interpreted correctly.

 - If so, policy applies.

- If misinterpreted or ambiguous or not applicable, RSAB may make a decision in the specific case, but then MUST refer it to WG

**Comment by stpeter** [comment]
This issue has been addressed in version -01 of the draft. @elear I suggest we can close this issue now.
