### ISSUE TITLE
Streams have content control.

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#6]
This is generally agreed. We may need specific text in a draft to note this.

**Comment by stpeter** [comment]
Proposed text:

Resolution of Disagreements between Authors and the RPC

During the process of editorial preparation and publication,
disagreements can arise between the authors of an RFC-to-be and the RPC.
In the main, such disagreements are handled quickly through direct
consultation between the parties; however, on occasion it is necessary
for a document shepherd, working group chair or research group chair, or
IETF Area Director to help reach agreement. In extremis (or where such
mediating individuals are not involved, as with the Independent Stream),
the relevant stream manager should intercede to achieve a resolution.

**Comment by csperkins** [comment]
Maybe "or IETF Area Director" -> "or the IESG or IRSG", otherwise looks good

**Comment by martinthomson** [comment]
This works pretty well, with Colin's amendment.
