### ISSUE TITLE
Resolution of disputes between the RPC and authors with cross-stream implications

### ISSUE THREAD

**Issue by JayDaley** [intarchboard/program-rfced-future#60]
Disputes between the RPC and authors sometimes need escalating and in the proposed process the stream manager appears to be the escalation point.  However, if the dispute is about something that affects all the streams, such as RFC style/policies, then it appears that this has to be escalated to the RSAB.  Is that correct and will the RSAB be able to respond in a timely manner?

**Comment by elear** [comment]
from chat): the RPC can decide whether the issue falls under existing policies and can apply that policy if they believe that it does. And can escalate to the RSAB if necessary, and the RSAB decides whether it falls under an existing policy, or if they need to refer to the WG to define a new policy. 

Peter to further elaborate.

**Comment by elear** [comment]
There is now text in Peter's draft.
