### ISSUE TITLE
Replacing the previous RSE role in gathering requirements for the RPC

### ISSUE THREAD

**Issue by JayDaley** [intarchboard/program-rfced-future#61]
Traditionally, the RSE has acted as the eyes and ears of the RPC, sharing insight and feedback about what they’re hearing from the community.  There are multiple times when the RSE brought community requirements to the RPC that the RPC were unaware of.  Is the RPC now required to do that directly or is that the responsibility of the RSWG/RSAB or do we assume that any requirements that are not brought to the RSWG are to be left unmet?

**Comment by elear** [comment]
There is related text proposed about the work program.  How is feedback collected about the work program, and does that answer this issue?  We're thinking "yes".  We may need some substantial explanatory text with perhaps a graph that shows process flow.  One issue might be priorities.  The concern would be- Program plan from RPC->Community-> differing priorities->issues with funding those priorities->no resolution.  To resolve this we might add some text obliging the LLC to fund mandates from the community.  Is that reasonable?  An LLC considerations section works for RFCs.  Will it work for a work program?  We need something for that.  More work needed.
