### ISSUE TITLE
Check to see if we need to update IRTF procedures

### ISSUE THREAD

**Issue by stpeter** [intarchboard/program-rfced-future#64]
Per comment from Colin Perkins in the May 2021 meeting

**Comment by csperkins** [comment]
http://irtf.org/policies for the list of IRTF process documents

**Comment by stpeter** [comment]
Thanks @csperkins - I'm not immediately seeing any need for IRTF procedures to be updated, other than the need to name someone to serve on the RSAB, which per https://github.com/intarchboard/program-rfced-future/issues/38 might be the IRTF chair (sorry!).

**Comment by csperkins** [comment]
Agreed – thanks.

**Comment by stpeter** [comment]
@elear It seems that this issue can be closed.
