### ISSUE TITLE
What counts as "community consensus"?

### ISSUE THREAD

**Issue by stpeter** [intarchboard/program-rfced-future#67]
The draft current says:

> Once consensus is established in the RSWG, the chairs shall issue a community call for comments. Should substantial comments be received, the RSWG will again consider those comments and make revisions as they see fit. At this same time, the RSAB will consider the proposal.

However, it's not clear what the "community" is here. Discussion is needed within the Program to clarify this.

**Comment by stpeter** [comment]
I think this is covered by Section 3.2.3: https://datatracker.ietf.org/doc/html/draft-iab-rfcefdp-rfced-model-01#section-3.2.3

**Comment by elear** [comment]
The specific thing that needs to be addressed is the behavior and expectations of the chairs.  Again, see issue #45.

**Comment by stpeter** [comment]
Right, see comment there.
