### ISSUE TITLE
All discussions on an open mailing list:

### ISSUE THREAD

**Issue by ekr** [intarchboard/program-rfced-future#68]

**Comment by ekr** [comment]
78 [RFC5378] and BCP 79 [RFC8179].  When the RSWG is formed, all
   discussions shall take place on an open email discussion list.
   Subsequently, the RSWG may decide by rough consensus to use
   additional tooling or forms of communication (e.g., GitHub as
   specified in [RFC8874]) as long as they are consistent with
   [RFC2418].

This is just a nit, but it seems like it formally precludes design teams w/o WG consensus. I would note that at IETF, the chairs can form design teams.

Also, it seems like it might preclude in person meetings.

Shall I proposed some text to weaken this a  bit?

**Comment by elear** [comment]
How about the following?

> When the RSWG is formed, all discussions shall take place on an open email discussion list or through in person meetings.  Subsequently, the RSWG may decide by rough consensus to use working methods(e.g., GitHub as specified in [RFC8874] or design teams) as long as they are consistent with [RFC2418].

**Comment by ekr** [comment]
This seems fine with me

**Comment by elear** [comment]
Please include text in -01 of the WG draft.

**Comment by stpeter** [comment]
Proposed text (sent on list):

> When the RSWG is formed, all discussions shall take place on an
> open email discussion list. Subsequently, the RSWG may decide by rough
> consensus to also use additional tooling (e.g., GitHub as specified in
> {{RFC8874}}), forms of communication (e.g., in-person or online
> meetings), and working methods (e.g., design teams) as long as they
> are consistent with {{RFC2418}}.

**Comment by stpeter** [comment]
Having seen no objections to this text, I suggest that the chairs can close this issue.
