### ISSUE TITLE
Limit corrective action?

### ISSUE THREAD

**Issue by ekr** [intarchboard/program-rfced-future#70]
S 3.2.4 says:
  The appeals body shall decide whether a process failure
   occurred and what if any corrective action should take place.

Is this unlimited? For instance, could the RSAB direct that a change be made to the document and then it be published even if there was strong WG consensus otherwise? I should think not.

**Comment by elear** [comment]
The current proposal is as follows:

> Decisions of the RSWG can only be appealed on grounds of failure to 
follow the correct process. Appeals should be made within 30 days of 
any action, or in the case of failure to act, of notice having been 
given to the RSWG. The RSAB will then decide if the process was 
followed and will direct RSWG chairs as to what procedural actions are 
required.
