### ISSUE TITLE
Who is responsible for creating new streams?

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#73]
I think this is actually an open question.  What is the process for creating a new stream?  Which body does that?  A stream usually itself represents an organization.  The RSAB wouldn't create orgs, tho perhaps they might recognize an org.

**Comment by stpeter** [comment]
I'm not sure this issue is in scope for the RFCED Future program.

**Comment by stpeter** [comment]
On list, Brian Carpenter suggested:

> The requirements and process for creating any additional RFC streams are 
out of scope in this document.

**Comment by elear** [comment]
Text is in Editor's copy.
