### ISSUE TITLE
Strategy body meetings are public

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#9]

**Comment by elear** [comment]
The current text specifies that the strategic body will not actually meet in person, but rather that business is to take place in electronic form.  A modest text change should reflect consensus that if any meetings do take place, proper notice must be given, and the public should be permitted to observe.  We needn't decide whether the body allows direct input during proceedings, but rather leave that to the body to decide, as circumstances warrant.

**Comment by elear** [comment]
Text tweak needed to ensure that we do not prohibit meetings and design teams by accident.

**Comment by stpeter** [comment]
Adrian's text was incorporated into version -01 of the draft so I suggest we can close this issue @elear
