### ISSUE TITLE
Should the 2418 backstop be more general

### ISSUE THREAD

**Issue by martinthomson** [intarchboard/program-rfced-future#90]
> Absent specific guidance in this document regarding the roles and responsibilities of the chairs, the general guidance provided in Section 6.1 of [RFC2418] should be considered appropriate.

Would it be better if this referred to the functioning of the group as a whole?  Such as,

> Absent specific guidance in this document regarding the functioning of the working group, the general guidance provided in Section 6.1 of [RFC2418] should be considered appropriate.

**Comment by stpeter** [comment]
We should change "6.1" to "6" because §6.1 is specifically about chairs, whereas other subsections of §6 talk about WG secretaries, design teams, etc.

**Comment by stpeter** [comment]
This change will be in -06

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/f6f3a36cd720dad6248e841a120b5c3b2e0fb226
