### ISSUE TITLE
Basis for appeals of RSAB decisions

### ISSUE THREAD

**Issue by martinthomson** [intarchboard/program-rfced-future#93]
The text on appeals of RSWG decisions says:

> Decisions of the RSWG can be appealed only on grounds of failure to follow the correct process.

The same text does not appear in the paragraph about the RSAB, but it does say:

> The IAB shall decide whether a process failure occurred and what if any corrective action should take place.

This might be confusing or it might be deliberate, I can't tell.

The RSAB makes two types of decision: policy approvals and decisions "related to implementation of policies already in force".  Is the intent to allow those decisions to be appealed?

**Comment by martinthomson** [comment]
Perhaps:

> Decisions of the RSAB can be appealed on grounds of failure to follow the correct process. Where the RSAB makes a decision in order to resolve a dispute, appeals can be filed on the basis that the RSAB misinterpreted an approved policy that was established by the RSWG. In other cases, disagreements about the conduct of the RSAB are not subject to appeal.

**Comment by elear** [comment]
No consensus. Back to the list for now.

**Comment by stpeter** [comment]
I now think Martin's text is fine.

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/dfea0158151a0b7c6149a4d3431c6f24d9f4f92f

**Comment by stpeter** [comment]
I think this is addressed in -06.
