### ISSUE TITLE
Who resolves disputes when they need to be timely?

### ISSUE THREAD

**Issue by martinthomson** [intarchboard/program-rfced-future#94]
> However, in the interest of time the disagreement may be resolved as the parties best see fit while the RSWG formulates a more general policy.

"the parties" is not quite specific enough.  I think that you want to pin this responsibility on the RSAB.  That suggests that an appeals path that is not exclusively process-based might be needed (see #93).

**Comment by martinthomson** [comment]
Proposed change:

> However, in the interest of time the RSAB may propose resolutions for disagreements after referring the matter to the RSWG to formulate a more general policy.

**Comment by martinthomson** [comment]
@stpeter suggested a rewrite of the entire paragraph:

> If the disagreement raises a new issue that is not covered by an
       existing policy or that cannot be resolved through consultation
       between the RPC and other relevant individuals and bodies (as
       described above), the RSAB should bring to the RSWG in order
       to formulate a new policy.  However, if needed, in the interest of
       time the RSAB is responsible for resolving the disagreement before
       a new policy is defined.

**Comment by elear** [comment]
See email on list.

**Comment by stpeter** [comment]
The text needs to be clearer. I will post on list.

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/f6f3a36cd720dad6248e841a120b5c3b2e0fb226

**Comment by stpeter** [comment]
I think this is addressed in -06.

**Comment by elear** [comment]
Sit tight.  We need to bring these back to the list for confirmation.
