### ISSUE TITLE
3-month timer restart?

### ISSUE THREAD

**Issue by larseggert** [intarchboard/program-rfced-future#97]
>* Voting on approval of policy documents produced by the RSWG shall
  be delayed until the vacancy or vacancies have been filled, up to a
  maximum of 3 months; this clause does not apply to a vacancy of the
  RSCE role, only of the stream representatives enumerated above.

In case of multiple vacancies, does the 3-month timer restart with vacancies that occur after the first?

**Comment by elear** [comment]
Accepted in meeting, to be confirmed on list, but specific text needed (and quickly).

**Comment by stpeter** [comment]
We need to say something like "If another person resigns, the timer needs to be reset."

**Comment by stpeter** [comment]
Fixed by https://github.com/intarchboard/program-rfced-future/commit/bcd7794794d484384ce284edfa36f3651bcdee1d
